#pragma once

#include "oz_interface.h"

#define RADIO_SOCKET_PATH "/tmp/socket_radioservice_interface"

#define OZ_RADIOSERVICE_GET_PS_STATE   1001
#define OZ_RADIOSERVICE_GET_RADIO_TECH 1002
#define OZ_RADIOSERVICE_GET_IMEI       1003
#define OZ_RADIOSERVICE_GET_IMEISV_SVN 1004
#define OZ_RADIOSERVICE_GET_NETWORK_NAME 1005
#define OZ_RADIOSERVICE_GET_REGI_STATE 1006
#define OZ_RADIOSERVICE_GET_SIGNAL_STRENGTH 1007
#define OZ_RADIOSERVICE_GET_OPERATION_MODE 1008
#define OZ_RADIOSERVICE_SET_OPERATION_MODE 1009
#define OZ_RADIOSERVICE_SET_FACTORY_RESET 1010
#define OZ_RADIOSERVICE_GET_NETWORK_SELECTION 1011
#define OZ_RADIOSERVICE_SET_NETWORK_SELECTION 1012
#define OZ_RADIOSERVICE_SEL_NETWORK_MANUAL 1013
#define OZ_RADIOSERVICE_GET_NETWORK_MODE 1014
#define OZ_RADIOSERVICE_SET_NETWORK_MODE 1015
#define OZ_RADIOSERVICE_GET_NETWORK_INFO_LIST 1016
#define OZ_RADIOSERVICE_GET_NRCDRX_MODE 1017
#define OZ_RADIOSERVICE_SET_NRCDRX_MODE 1018
// LGP_5G_MODULE_DEBUG_SCREEN [START]
#define OZ_RADIOSERVICE_GET_DEBUG_SCREEN 1019
// LGP_5G_MODULE_DEBUG_SCREEN [END]
#define OZ_RADIOSERVICE_PS_REGISTRATION_CHANGED 2001
#define OZ_RADIOSERVICE_RAT_CHANGED 2002

void oz_radioservice_rpc_handler(const void* hChHandle, int aReq, RES_OBJ aInObj, REQ_OBJ aOutObj);

