#pragma once

#include "oz_interface.h"

#define QCMAPIF_SOCKET_PATH "/tmp/socket_qcmapifservice_interface"

#define OZ_QCMAPIFSERVICE_SET_MOBILEAP                  1000
#define OZ_QCMAPIFSERVICE_GET_MOBILEAP                  1001
#define OZ_QCMAPIFSERVICE_GET_DMZ                       1002
#define OZ_QCMAPIFSERVICE_ADD_DMZ                       1003
#define OZ_QCMAPIFSERVICE_DEL_DMZ                       1004
#define OZ_QCMAPIFSERVICE_GET_WAN_PING_BLOCK            1005
#define OZ_QCMAPIFSERVICE_SET_WAN_PING_BLOCK            1006
#define OZ_QCMAPIFSERVICE_GET_PROFILE                   1007
#define OZ_QCMAPIFSERVICE_SET_PROFILE                   1008
#define OZ_QCMAPIFSERVICE_GET_WAN_STATE                 1009
#define OZ_QCMAPIFSERVICE_CONNECT_BACKHAUL              1010
#define OZ_QCMAPIFSERVICE_DISCONNECT_BACKHAUL           1011
#define OZ_QCMAPIFSERVICE_GET_DATA_ENABLED              1012
#define OZ_QCMAPIFSERVICE_SET_DATA_ENABLED              1013
#define OZ_QCMAPIFSERVICE_GET_ROAMING_DATA_ENABLED      1014
#define OZ_QCMAPIFSERVICE_SET_ROAMING_DATA_ENABLED      1015
#define OZ_QCMAPIFSERVICE_GET_APN_NAME                  1016
#define OZ_QCMAPIFSERVICE_GET_PROFILE_NAME              1017
#define OZ_QCMAPIFSERVICE_UPDATE_APN_INFO               1018
#define OZ_QCMAPIFSERVICE_GET_PORT_FORWARDING           1019
#define OZ_QCMAPIFSERVICE_ADD_PORT_FORWARDING           1020
#define OZ_QCMAPIFSERVICE_DEL_PORT_FORWARDING           1021

#define OZ_QCMAPIFSERVICE_NOTIFY_MOBILEAP_STATECHANGED  1100
#define OZ_QCMAPIFSERVICE_NOTIFY_WAN_STATECHANGED       1101

// uicc 1200 ~
#define OZ_QCMAPIFSERVICE_GET_MCC_MNC           1201
#define OZ_QCMAPIFSERVICE_GET_GID               1202
#define OZ_QCMAPIFSERVICE_GET_IMSI              1203
#define OZ_QCMAPIFSERVICE_GET_ICCID             1204
#define OZ_QCMAPIFSERVICE_GET_MSISDN            1205
#define OZ_QCMAPIFSERVICE_GET_SIM_STATE         1206
#define OZ_QCMAPIFSERVICE_SET_ACTIVATION        1207
#define OZ_QCMAPIFSERVICE_GET_SIM_PIN_STATUS    1208
#define OZ_QCMAPIFSERVICE_GET_PINBLOCKTRYCNT    1209
#define OZ_QCMAPIFSERVICE_SET_PINENABLE         1210
#define OZ_QCMAPIFSERVICE_SIM_ISVERIFY          1211
#define OZ_QCMAPIFSERVICE_SIM_CHANGEPINCODE     1212
#define OZ_QCMAPIFSERVICE_SIM_UNBLOCKPUKCODE    1213

//radio 1300 ~
// [START] radio service 
#define OZ_QCMAPIFSERVICE_GET_NETWORK_MODE      1301
#define OZ_QCMAPIFSERVICE_SET_NETWORK_MODE      1302
#define OZ_QCMAPIFSERVICE_GET_NRCDRX_MODE       1303
#define OZ_QCMAPIFSERVICE_SET_NRCDRX_MODE       1304
#define OZ_QCMAPIFSERVICE_GET_DEBUG_SCREEN      1305 // LGP_5G_MODULE_DEBUG_SCREEN - QCMAP
#define OZ_QCMAPIFSERVICE_GET_RADIO_TECH        1306
#define OZ_QCMAPIFSERVICE_GET_NETWORK_NAME      1307
// [END] radio service

//WIFI 1400 ~
#define OZ_QCMAPIFSERVICE_ACTIVATE_WLAN         1400
#define OZ_QCMAPIFSERVICE_ENABLE_WLAN           1401
#define OZ_QCMAPIFSERVICE_SET_WLAN_CONFIG       1402

void oz_qcmapifservice_rpc_handler(const void* hChHandle, int aReq, RES_OBJ aInObj, REQ_OBJ aOutObj);

